INSERT INTO LOG_CLOUD_STARTUP_CONFIG (OWNING_RECOVERY_DOMAIN_NAME, PROPERTY_NAME, PROPERTY_VALUE) values ('logcloud', 'com.atomikos.icatch.max_timeout', '300000');
INSERT INTO LEADER (OWNING_RECOVERY_DOMAIN_NAME) select ('logcloud') WHERE NOT EXISTS (select 1 from LEADER); -- EXPIRY defaults to 0
